BajiDeveloperEdition/src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CEO__c</fullName>
        <label>CEO</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BajiDeveloperEdition/src/classes/ClassSet.cls
public class ClassSet 
{
    public Company__C Company {get;set;}      
    public ClassSet() 
    {    
        Id id = ApexPages.currentPage().getParameters().get('id');
        if(id == null)        
           Company = new Company__C();
        else
            Company = [SELECT Company__C.Name, Company__C.Address__c, Company__C.CEO__c FROM Company__C WHERE id = :id];
        
    } 
    public pageReference save()
    {
    try
    {
         if(Company.id == null)
             insert Company;
         else    
            update company;
        PageReference pageRef = new PageReference('/'+Company.id);    
        pageRef.setRedirect(true);
        return pageRef;
    }
    Catch (exception e)
    {
        return null;
    }
   }
}