BajiDeveloperEdition/src/objects/Foundation_Countries__c.object
<CustomObject>
    <label>Foundation_Countries</label>
    <nameField>
        <label>Foundation_Countries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foundation_Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BajiDeveloperEdition/src/objects/Foundation_States__c.object
<CustomObject>
    <fields>
        <fullName>Foundation_Countries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Foundation_Countries</label>
        <referenceTo>Foundation_Countries__c</referenceTo>
        <relationshipLabel>Foundation_States</relationshipLabel>
        <relationshipName>Foundation_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Foundation_States</label>
    <nameField>
        <label>Foundation_States Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foundation_States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BajiDeveloperEdition/src/classes/dependenpick.cls
public class dependenpick {

    public String State { get; set; }

    public String Country { get; set; }
    
    public List<SelectOption> getCountries()
    {
        List<SelectOption> optionlist1 = new List<SelectOption>();
        
        list<Foundation_Countries__c> Ocountries = new list<Foundation_Countries__c>();
        Ocountries = [select id,Name from Foundation_Countries__c];
        
        for(Foundation_Countries__c Ocounty : Ocountries)
        {
            optionlist1.add(new SelectOption(Ocounty.id,Ocounty.Name));
        }
        return optionlist1;    
    }
    public List<Foundation_States__c> getStates()
     {
         List<Foundation_States__c> optionList = new List<Foundation_States__c>();
         
         list<Foundation_States__c> Ostates = new list<Foundation_States__c>();
         Ostates  = [SELECT id,Name,State_Code__c FROM Foundation_States__c];
         if(Country == 'India')
          {        
                  
                    optionList = [SELECT id,Name,State_Code__c FROM Foundation_States__c where Name='AndhraPradesh'];                                                                     
          } 
          /*else if(Country == 'SouthAfrica')
          {
              
          } 
          else
          {
              optionList.add(new SelectOption('None','None'));
              for(Foundation_States__c Ostate : Ostates)
                {
                    optionList.add(new SelectOption(Ostate.id,Ostate.Name));
                }
          } */
             return optionList;
      } 

}