BajiDeveloperEdition/src/objects/Foundation_Countries__c.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country_Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Foundation_Countries</label>
    <nameField>
        <label>Foundation_Countries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foundation_Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BajiDeveloperEdition/src/classes/Parent_Child.cls
public class Parent_Child {

   
    
    public Parent_Child(){
        
        con = new Contact();    
    }
    
    public PageReference loading_values() {
      if(con!=null){
         Account a=[select id,name,ParentID, billingstreet, billingCity from account where ID=:con.accountid];
         con.mailingstreet=a.billingstreet;
        }
        return null;
    }

    public contact con { get; set; }
    
     public Foundation_Countries__c getCountryCode() {
         
         return([select Country_Code__c from Foundation_Countries__c where Name = 'India']);
     }
    
}