BajiDeveloperEdition/src/objects/Foundation_Countries__c.object
<CustomObject>
    <label>Foundation_Countries</label>
    <nameField>
        <label>Foundation_Countries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foundation_Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BajiDeveloperEdition/src/objects/Foundation_States__c.object
<CustomObject>
    <fields>
        <fullName>Foundation_Countries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Foundation_Countries</label>
        <referenceTo>Foundation_Countries__c</referenceTo>
        <relationshipLabel>Foundation_States</relationshipLabel>
        <relationshipName>Foundation_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Foundation_States</label>
    <nameField>
        <label>Foundation_States Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foundation_States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BajiDeveloperEdition/src/classes/Scontrol.cls
public class Scontrol {

    public String States { get; set; }
    public String Id { get; set; }
    private List<Foundation_States__c> States_list = new List<Foundation_States__c>();
    
    public Scontrol(){
    
    States_list = [SELECT  id,
                              Name,
                              State_Code__c,
                              Foundation_Countries__c 
                      FROM 
                              Foundation_States__c
                      WHERE     
                              Foundation_Countries__c != null   
                      ];
    }
    public List<selectOption> getStates()
     {
      //system.debug('***CheckC Id Value------'+Id);
         List<selectOption> optionList = new List<selectOption>();
         
        if(Id  != null || Id != '')
        {
            for(Foundation_States__c Ostate : States_list )
            {
                   //system.debug('*****Country ID******'+Ostate.Foundation_Countries__c);
                     
                             if(Ostate.Foundation_Countries__c == Id )
                          { 
                          //system.debug('*****Country String******'+Country);                             
                            optionList.add(new selectOption(Ostate.id,Ostate.name));                                                                     
                          }
                                             
             }// end for loop
         }
                  
             return optionList;
      }

}