BajiDeveloperEdition/src/objects/Foundation_Countries__c.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country_Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Foundation_Countries</label>
    <nameField>
        <label>Foundation_Countries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foundation_Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BajiDeveloperEdition/src/objects/Foundation_States__c.object
<CustomObject>
    <fields>
        <fullName>Foundation_Countries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Foundation_Countries</label>
        <referenceTo>Foundation_Countries__c</referenceTo>
        <relationshipLabel>Foundation_States</relationshipLabel>
        <relationshipName>Foundation_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Foundation_States</label>
    <nameField>
        <label>Foundation_States Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foundation_States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BajiDeveloperEdition/src/classes/TestClass1.cls
@isTest
public class TestClass1
{


    private static testMethod  void Runme1()
    {
        List<Foundation_Countries__c> Found_list = new List<Foundation_Countries__c>();
              Foundation_Countries__c ofound1 = new Foundation_Countries__c(Name='India',Country_Code__c='IN');       
              Foundation_Countries__c ofound2 = new Foundation_Countries__c(Name='Pakistan',Country_Code__c='Pak');                     
              Foundation_Countries__c ofound3 = new Foundation_Countries__c(Name='Srilanka',Country_Code__c='SLK');                     
              Foundation_Countries__c ofound4 = new Foundation_Countries__c(Name='China',Country_Code__c='CHN');      
        Found_list.add(ofound1);              
        Found_list.add(ofound2);              
        Found_list.add(ofound3);              
        Found_list.add(ofound4);              
            insert Found_list;
            
            Foundation_States__c OfoundState = new Foundation_States__c(Name='AP',Foundation_Countries__c=Found_list[0].Id);
             insert OfoundState;
            // system.debug('Foundation Countries'+Found_list);
        DependentObjects Dep = new DependentObjects ();
                    Dep.getCountries();
                    Dep.Country = Found_list[3].Id; 
                    Dep.getStates();
                    Dep.main();
               
                    
    } 
 
}